CREATE OR REPLACE STREAM USERS WITH (KAFKA_TOPIC='example_avro', VALUE_FORMAT='AVRO')
AS SELECT * , UCASE('Platform') FROM USERS;

CREATE TABLE USERS_PER_HOUR WITH (KAFKA_TOPIC='USERS_PER_HOUR', PARTITIONS=6, REPLICAS=1, VALUE_AVRO_SCHEMA_FULL_NAME='users.per.hour.Avro') AS SELECT
  TIMESTAMPTOSTRING(WINDOWSTART, 'yyyy-MM-dd''T''HH:mm:ssZ', 'GMT') WINDOW_START_TS,
  USERS.PLATFORM PLATFORM,
  COUNT(*) USERS_AMOUNT
FROM USERS USERS
WINDOW TUMBLING ( SIZE 1 HOURS ) 
GROUP BY USERS.PLATFORM
EMIT CHANGES;